In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Initializing molecules

## Methanediol

In [2]:
Ionpos_Methanediol_ang_nc=[[ 1.35170 ,  -0.08370,    0.00000  ], 
                    [-0.52950,    1.24650 ,  -0.00000  ], 
                    [-0.06950,   -0.09830,   -0.00000  ],
                    [-0.43450 ,  -0.61450  ,  0.88910  ],
                    [-0.43450 ,  -0.61450 ,  -0.88910 ],
                    [1.62470 ,  -1.02540  ,  0.00000  ],
                    [-1.50830 ,   1.19000  ,  0.00000]]
ions_Methanediol=['O','O','C','H','H','H','H']

In [3]:
Ionpos_Methanediol_ang_nr= Ionpos_Methanediol_ang_nc-np.array([-0.43450 ,  -0.61450 ,  -0.88910])
print(Ionpos_Methanediol_ang_nr)

[[ 1.7862  0.5308  0.8891]
 [-0.095   1.861   0.8891]
 [ 0.365   0.5162  0.8891]
 [ 0.      0.      1.7782]
 [ 0.      0.      0.    ]
 [ 2.0592 -0.4109  0.8891]
 [-1.0738  1.8045  0.8891]]


In [4]:
b=np.mat([0,0,1])
a=np.mat([ 0.365 ,  0.5162 , 0.8891])
a=a/np.sqrt(np.dot(a,a.T))
c=np.dot(a,b.T)
v=np.cross(a,b)[0]
s=np.sqrt(np.dot(v,v.T))
y = np.mat([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

Rot_Methanediol=np.mat(np.diag([1,1,1]))+y+np.dot(y,y)*(((1-c)/s**2)[0,0])
Ionpos_Methanediol_ang=np.array(np.dot(Rot_Methanediol,np.mat(Ionpos_Methanediol_ang_nr.T))).T

In [5]:
#Converting to the bond length of platinum
Ionpos_Methanediol_ang=Ionpos_Methanediol_ang+np.array([0,0,2.13000])-Ionpos_Methanediol_ang[list(ions_Methanediol).index('C')]
Ionpos_Methanediol_ang

array([[ 1.33227576e+00, -1.11160797e-01,  2.61239731e+00],
       [-5.48926136e-01,  1.21903652e+00,  2.61240762e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.13000000e+00],
       [-5.94930187e-01, -8.41377980e-01,  2.48822816e+00],
       [-2.57868748e-17, -6.66570706e-17,  1.03904342e+00],
       [ 1.67057573e+00, -9.60510543e-01,  2.25815724e+00],
       [-1.46243179e+00,  1.25487883e+00,  2.25819801e+00]])

In [6]:
Ionpos_Methanediol_ang=array([[ 1.33227576e+00, -1.11160797e-01,  2.61239731e+00],
       [-5.48926136e-01,  1.21903652e+00,  2.61240762e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.13000000e+00],
       [-5.94930187e-01, -8.41377980e-01,  2.48822816e+00],
       [ 1.67057573e+00, -9.60510543e-01,  2.25815724e+00],
       [-1.46243179e+00,  1.25487883e+00,  2.25819801e+00]])
ions_Methanediol=['O','O','C','H','H','H']

## Formaldehyde

In [7]:
 Ionpos_Formaldehyde_ang_nc=np.array([[ 0.000000   ,  .000000   ,  .683501],
            [.000000   ,  .000000 ,   -.536614],
            [.000000  ,   .934390  , -1.124164],
            [.000000  ,  -.934390  , -1.124164]])
ions_Formaldehyde=['O','C','H','H']

In [8]:
Ionpos_Formaldehyde_ang_nr= Ionpos_Formaldehyde_ang_nc-np.array([.000000  ,  -.934390  , -1.124164])
print(Ionpos_Formaldehyde_ang_nr)

[[0.       0.93439  1.807665]
 [0.       0.93439  0.58755 ]
 [0.       1.86878  0.      ]
 [0.       0.       0.      ]]


In [9]:
b=np.mat([0,0,1])
a=np.mat([0.     ,  0.93439 , 0.58755 ])
a=a/np.sqrt(np.dot(a,a.T))
c=np.dot(a,b.T)
v=np.cross(a,b)[0]
s=np.sqrt(np.dot(v,v.T))
y = np.mat([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

Rot_Formaldehyde=np.mat(np.diag([1,1,1]))+y+np.dot(y,y)*(((1-c)/s**2)[0,0])
Ionpos_Formaldehyde_ang=np.array(np.dot(Rot_Formaldehyde,np.mat(Ionpos_Formaldehyde_ang_nr.T))).T
print(Ionpos_Formaldehyde_ang)

[[ 0.00000000e+00 -1.03288479e+00  1.75325025e+00]
 [ 0.00000000e+00  5.58582516e-17  1.10376613e+00]
 [ 0.00000000e+00  9.94777478e-01  1.58201026e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]


In [10]:
#Converting to the bond length of platinum
Ionpos_Formaldehyde_ang=Ionpos_Formaldehyde_ang+np.array([0,0,2.13000])-Ionpos_Formaldehyde_ang[list(ions_Formaldehyde).index('C')]
print(Ionpos_Formaldehyde_ang)

[[ 0.00000000e+00 -1.03288479e+00  2.77948411e+00]
 [ 0.00000000e+00  0.00000000e+00  2.13000000e+00]
 [ 0.00000000e+00  9.94777478e-01  2.60824413e+00]
 [ 0.00000000e+00 -5.58582516e-17  1.02623387e+00]]


In [11]:
Ionpos_Formaldehyde_ang=array([[ 0.00000000e+00, -1.03288479e+00,  2.77948411e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.13000000e+00],
       [ 0.00000000e+00,  9.94777478e-01,  2.60824413e+00]])
ions_Formaldehyde=['O','C','H']

## Carbon dioxide 

In [12]:
Ionpos_CO2_ang_nr=np.array([[ 0.000000  ,  0.000000 ,0.000000],
                            [0.00000, 0.000000   , 1.159076],
                            [ 0.000000   , 0.000000  , -1.159076]])
ions_CO2=['C','O','O']

In [13]:
b=np.mat([1,0,0])
a=np.mat([0.     ,  0 , 1 ])
a=a/np.sqrt(np.dot(a,a.T))
c=np.dot(a,b.T)
v=np.cross(a,b)[0]
s=np.sqrt(np.dot(v,v.T))
y = np.mat([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

Rot_CO2=np.mat(np.diag([1,1,1]))+y+np.dot(y,y)*(((1-c)/s**2)[0,0])
Ionpos_CO2_ang=np.array(np.dot(Rot_CO2,np.mat(Ionpos_CO2_ang_nr.T))).T
Ionpos_CO2_ang=Ionpos_CO2_ang+1.3*np.array([0,0,2.13000])
Ionpos_CO2_ang

array([[ 0.      ,  0.      ,  2.769   ],
       [ 1.159076,  0.      ,  2.769   ],
       [-1.159076,  0.      ,  2.769   ]])

## Formic acid

In [14]:
Ionpos_Formic_acid_ang_nc=np.array([[0.7910  ,   -0.0921   ,   1.3425],
   [0.3208  ,   -0.0411   ,   0.3549],
   [0.8042   ,  -0.1358   ,  -0.7518],
   [-1.0065  ,    0.1597   ,   0.4283],
   [-1.4043   ,   0.2023  ,   -0.4370]])  
ions_Formic_acid=['H','C','O','O','H']

In [15]:
b=np.mat([0,0,1])
a=np.mat(np.cross(Ionpos_Formic_acid_ang_nc[1]-Ionpos_Formic_acid_ang_nc[0], Ionpos_Formic_acid_ang_nc[2]-Ionpos_Formic_acid_ang_nc[0])) #the molecule is planar, we rotate to set the normal vector of the plane to line up with the z axis
a=a/np.sqrt(np.dot(a,a.T))
c=np.dot(a,b.T)
v=np.cross(a,b)[0]
s=np.sqrt(np.dot(v,v.T))
y = np.mat([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

Rot_Formic_acid=np.mat(np.diag([1,1,1]))+y+np.dot(y,y)*(((1-c)/s**2)[0,0])
Ionpos_Formic_acid_ang=np.array(np.dot(Rot_Formic_acid,np.mat(Ionpos_Formic_acid_ang_nc.T))).T
Ionpos_Formic_acid_ang=Ionpos_Formic_acid_ang+1.3*np.array([0,0,2.13000])
Ionpos_Formic_acid_ang

array([[ 0.98664014,  1.20954987,  2.76895296],
       [ 0.3725139 ,  0.30296741,  2.76895296],
       [ 0.69463083, -0.86479508,  2.76895296],
       [-0.94406658,  0.57508739,  2.76910862],
       [-1.46797623, -0.22135619,  2.76906337]])

## Carbon Monoxide 

In [16]:
Ionpos_CO_ang_nc=[[ 0.00000 ,  0.00000,    0.00000  ], 
                    [0.00000,    0.00000 ,  1.21000  ]]
ions_CO=['C','O']
Ionpos_CO_ang=Ionpos_CO_ang_nc+np.array([0,0,1.9])

## Oxigen

In [17]:
Ionpos_O_ang_nc=np.array([[ 0.00000 ,  0.00000,    0.00000  ]])
ions_O=['O']
Ionpos_O_ang=Ionpos_O_ang_nc+np.array([0,0,1.9])

##  hydroperoxil 

In [18]:
Ionpos_HO2_1_ang_nc=np.array([[ 	0.0611, 	0.0000, 	-0.6414],
    [0.0611, 	0.0000, 	0.7476],
	[-0.9779,	0.0000, 	-0.8497]])
Ionpos_HO2_1_ang_nc=Ionpos_HO2_1_ang_nc-Ionpos_HO2_1_ang_nc[0]
ions_HO2_1=['O','O','H']


In [19]:
b=np.mat([0,0,-1])
a=np.mat(np.cross(Ionpos_HO2_1_ang_nc[2]-Ionpos_HO2_1_ang_nc[1],np.cross(Ionpos_HO2_1_ang_nc[0]-Ionpos_HO2_1_ang_nc[1],Ionpos_HO2_1_ang_nc[2]-Ionpos_HO2_1_ang_nc[0]))) #the molecule is planar, we rotate to set the normal vector of the plane to line up with the z axis
a=a/np.sqrt(np.dot(a,a.T))
c=np.dot(a,b.T)
v=np.cross(a,b)[0]
s=np.sqrt(np.dot(v,v.T))
y = np.mat([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

Rot_HO2_1=np.mat(np.diag([1,1,1]))+y+np.dot(y,y)*(((1-c)/s**2)[0,0])
Ionpos_HO2_1_ang=np.array(np.dot(Rot_HO2_1,np.mat(Ionpos_HO2_1_ang_nc.T))).T
Ionpos_HO2_1_ang=Ionpos_HO2_1_ang+np.array([0,0,1.9])
Ionpos_HO2_1_ang

array([[ 0.        ,  0.        ,  1.9       ],
       [ 1.16434664,  0.        ,  2.65737567],
       [-0.74114235,  0.        ,  2.65737567]])

In [20]:
Ionpos_HO2_2_ang_nc=np.array([[ 	0.0611, 	0.0000, 	-0.6414],
    [0.0611, 	0.0000, 	0.7476],
	[-0.9779,	0.0000, 	-0.8497]])
Ionpos_HO2_2_ang_nc=Ionpos_HO2_2_ang_nc-Ionpos_HO2_2_ang_nc[1]
ions_HO2_2=['O','O','H']


In [21]:

Ionpos_HO2_2_ang=np.array(-np.mat(Ionpos_HO2_2_ang_nc.T)).T
Ionpos_HO2_2_ang=Ionpos_HO2_2_ang+np.array([0,0,1.9000])
Ionpos_HO2_2_ang

array([[0.    , 0.    , 3.289 ],
       [0.    , 0.    , 1.9   ],
       [1.039 , 0.    , 3.4973]])

## Hydroxide 

In [22]:
Ionpos_OH_ang_nc=[[ 0.00000 ,  0.00000,    0.00000  ],[ 0.00000 ,  0.00000,    0.98 ]]
ions_OH=['O','H']
Ionpos_OH_ang=Ionpos_OH_ang_nc+np.array([0,0,1.9])

### appending all molecules and groups

In [23]:
Ionpos_Mols=[Ionpos_O_ang,Ionpos_HO2_1_ang, Ionpos_HO2_2_ang,Ionpos_OH_ang]
ion_symb=[ions_O,ions_HO2_1,ions_HO2_2,ions_OH]

# Initializing lattices

In [24]:
filename='lattices.dat'
f=open(filename)
latts=f.readlines()
f.close()
lattices=[lat[:-1] for lat in latts]
lati=[la.split() for la in lattices]
latman=np.array([[float(i) for i in j] for j in lati])
latman[:,:3]=latman[:,:3]*0.529177
latman_Bohr=np.array([[float(i) for i in j] for j in lati])
#latman_Bohr[:,:3]=1.88973*latman_Bohr[:,:3] ## convert to bohr
latman_Bohr[:,:3]=latman_Bohr[:,:3] ## convert to bohr
print(latman_Bohr)


[[18.86376392 10.89100622 40.01618549 90.         90.         90.        ]
 [18.86376392 10.89100622 40.01618549 90.         90.         90.        ]
 [18.86376392 10.89100622 40.01618549 90.         90.         90.        ]
 [18.86376392 10.89100622 40.01618549 90.         90.         90.        ]]


In [25]:
print(latman_Bohr)
f=open(filename)
lattnames=f.readlines()[::5]
print(lattnames)

[[18.86376392 10.89100622 40.01618549 90.         90.         90.        ]
 [18.86376392 10.89100622 40.01618549 90.         90.         90.        ]
 [18.86376392 10.89100622 40.01618549 90.         90.         90.        ]
 [18.86376392 10.89100622 40.01618549 90.         90.         90.        ]]
['18.8637639202  10.8910062229 40.0161854853  90.0000  90.0000 90.0000\n']


In [26]:
##making the lattice files for input
for i in range(len(latman_Bohr)):
    file = open('111_'+str(i)+'/spinel111.lattice', 'w')
    file.write('lattice Triclinic '+str(latman_Bohr[i])[1:-6]) 
    file.close()

In [27]:
### change of basis matrices
Chang=[]
for lat in latman:
    alph=radians(lat[3])
    bet=radians(lat[4])
    gamm=radians(lat[5])
    a=lat[0]
    b=lat[1]
    c=lat[2]
    Omega=a*b*c*np.sqrt(1-cos(alph)*cos(alph)-cos(bet)*cos(bet)-cos(gamm)*cos(gamm)+2*cos(alph)*cos(bet)*cos(gamm))
    Mat=[[1/a, -cos(gamm)/(a*sin(gamm)),b*c*(cos(alph)-cos(bet)*cos(gamm))/(Omega*sin(gamm))],[0, 1/(b*sin(gamm)),-a*c*(cos(alph)-cos(bet)*cos(gamm))/(Omega*sin(gamm))],[0,0,a*b*sin(gamm)/Omega]]
    Chang.append(Mat)
    


# Initialize Pt fractional coords

In [28]:
Pt=loadtxt("fracoords.dat")
print(Pt)

[[0.33333 0.      0.02778]
 [0.83333 0.5     0.02778]
 [0.74083 0.77751 0.05861]
 [0.24083 0.27751 0.05861]
 [0.24083 0.72249 0.05861]
 [0.74083 0.22249 0.05861]
 [0.51834 0.      0.05861]
 [0.01834 0.5     0.05861]
 [0.      0.      0.06473]
 [0.5     0.5     0.06473]
 [0.83333 0.      0.11112]
 [0.33333 0.5     0.11112]
 [0.58333 0.25    0.11112]
 [0.08333 0.75    0.11112]
 [0.58333 0.75    0.11112]
 [0.08333 0.25    0.11112]
 [0.5     0.      0.88889]
 [0.      0.5     0.88889]
 [0.25    0.25    0.88889]
 [0.75    0.75    0.88889]
 [0.25    0.75    0.88889]
 [0.75    0.25    0.88889]
 [0.33333 0.      0.93528]
 [0.83333 0.5     0.93528]
 [0.0925  0.27751 0.94138]
 [0.5925  0.77751 0.94138]
 [0.31499 0.5     0.94138]
 [0.81499 0.      0.94138]
 [0.5925  0.22249 0.94138]
 [0.0925  0.72249 0.94138]
 [0.      0.      0.97222]
 [0.5     0.5     0.97222]
 [0.66667 0.      1.     ]
 [0.16667 0.5     1.     ]]


In [30]:
for i in range(len(latman)):
    for j in range(5):
        
        file = open('spinel111_mol'+'_'+str(j)+'.ionpos', 'w')
        change_basis=dot(Chang[i],Ionpos_Mols[j].T).T+0.5*(np.array( [0.33333  ,  0.5     ,   0.11112   ]) +np.array( [0.08333  ,  0.25  ,     0.11112   ])  ) 
        #print(j,'\n','\n',dot(Chang[i],Ionpos_Mols[j].T).T,'\n','\n',change_basis,'\n','\n',Ionpos_Mols[j])
        for k in range(size(ion_symb[j])):
            file.write('ion '+ion_symb[j][k]+' ' )
            print('ion '+ion_symb[j][k]+' ')
            for q in range(len(change_basis[k])):
                file.write("%.5f" % change_basis[k][q]+ ' ')
            file.write('1 \n')
            
        

ion O 
ion O 
ion O 
ion H 
ion O 
ion O 
ion H 
ion O 
ion H 


IndexError: list index out of range

In [39]:
sum(0.5*(np.array( [0.33333   , 0.5     ,  0   ]) -np.array( [0.08333  ,  0.25  ,     0  ])  ) *0.5*(np.array( [0.33333   , 0.5     ,  0   ]) -np.array( [0.08333  ,  0.25  ,     0  ])  )) 
sqrt(1.9**2 -0.03125)

1.8917584412392614

In [93]:
size(Ionpos_Mols)

4

In [248]:
for i in range(len(Ionpos_Formaldehyde_ang)):
    print('Ion '+ions_Formaldehyde[i], end=' ' )
    for j in range(len(Ionpos_Formaldehyde_ang[i])):
        print("%.3f" % Ionpos_Formaldehyde_ang[i][j], end = ' ')
    print('\n')

Ion O 0.000 -1.033 2.779 

Ion C 0.000 0.000 2.130 

Ion H 0.000 0.995 2.608 

Ion H 0.000 -0.000 1.026 



In [236]:
for i in range(len(Ionpos_Methanediol_ang)):
    print('Ion '+ions_Methanediol[i], end=' ' )
    for j in range(len(Ionpos_Methanediol_ang[i])):
        print("%.3f" % Ionpos_Methanediol_ang[i][j], end = ' ')
    print('\n')

Ion O 1.332 -0.111 2.612 

Ion O -0.549 1.219 2.612 

Ion C 0.000 0.000 2.130 

Ion H -0.595 -0.841 2.488 

Ion H 1.671 -0.961 2.258 

Ion H -1.462 1.255 2.258 



In [218]:
for i in range(len(Ionpos_Formic_acid_ang)):
    print('Ion '+ions_Formic_acid[i], end=' ' )
    for j in range(len(Ionpos_Formic_acid_ang[i])):
        print("%.3f" % Ionpos_Formic_acid_ang[i][j], end = ' ')
    print('\n')


Ion H 0.987 1.210 3.195 

Ion C 0.373 0.303 3.195 

Ion O 0.695 -0.865 3.195 

Ion O -0.944 0.575 3.195 

Ion H -1.468 -0.221 3.195 



In [219]:

for i in range(len(Ionpos_CO2_ang)):
    print('Ion '+ions_CO2[i], end=' ' )
    for j in range(len(Ionpos_CO2_ang[i])):
        print("%.3f" % Ionpos_CO2_ang[i][j], end = ' ')
    print('\n')

Ion C 0.000 0.000 2.556 

Ion O 1.159 0.000 2.556 

Ion O -1.159 0.000 2.556 



In [220]:
Ionpos_Formaldehyde_p=np.array(Ionpos_Formaldehyde_ang)-array(Ionpos_Formaldehyde_ang[-1])
Ionpos_Methanediol_p=np.array(Ionpos_Methanediol_ang)-array(Ionpos_Methanediol_ang[4])
Ionpos_Formic_acid_p=np.array(Ionpos_Formic_acid_ang)-array(Ionpos_Formic_acid_ang[1])
Ionpos_CO2_p=np.array(Ionpos_CO2_ang)
for i in range(len(Ionpos_Formaldehyde_p)):
    print('Ion '+ions_Formaldehyde[i], end=' ' )
    for j in range(len(Ionpos_Formaldehyde_p[i])):
        print("%.3f" % Ionpos_Formaldehyde_p[i][j], end = ' ')
    print('\n')
print('__________________________')
for i in range(len(Ionpos_Methanediol_p)):
    print('Ion '+ions_Methanediol[i], end=' ' )
    for j in range(len(Ionpos_Methanediol_p[i])):
        print("%.3f" % Ionpos_Methanediol_p[i][j], end = ' ')
    print('\n')
    
print('__________________________')
for i in range(len(Ionpos_Formic_acid_p)):
    print('Ion '+ions_Formic_acid[i], end=' ' )
    for j in range(len(Ionpos_Formic_acid_p[i])):
        print("%.3f" % Ionpos_Formic_acid_p[i][j], end = ' ')
    print('\n')
print('__________________________')
for i in range(len(Ionpos_CO2_p)):
    print('Ion '+ions_CO2[i], end=' ' )
    for j in range(len(Ionpos_CO2_p[i])):
        print("%.3f" % Ionpos_CO2_p[i][j], end = ' ')
    print('\n')

Ion O 0.000 -1.033 1.753 

Ion C 0.000 0.000 1.104 

Ion H 0.000 0.995 1.582 

Ion H 0.000 0.000 0.000 

__________________________
Ion O -0.338 0.849 0.354 

Ion O -2.220 2.180 0.354 

Ion C -1.671 0.961 -0.128 

Ion H -2.266 0.119 0.230 

Ion H 0.000 0.000 0.000 

Ion H -3.133 2.215 0.000 

__________________________
Ion H 0.614 0.907 0.000 

Ion C 0.000 0.000 0.000 

Ion O 0.322 -1.168 0.000 

Ion O -1.317 0.272 0.000 

Ion H -1.840 -0.524 0.000 

__________________________
Ion C 0.000 0.000 2.556 

Ion O 1.159 0.000 2.556 

Ion O -1.159 0.000 2.556 



In [23]:
#conversion factors
a_Pt=0.392 #nm
a_Pt_ang=a_Pt*10 #angstrom
a_Pt_ang1=2*a_Pt_ang/sqrt(2) #angstrom
a_Pt_ang2=2*a_Pt_ang/sqrt(2)#angstrom
a_Pt_ang3=6*a_Pt_ang #angstrom

print(a_Pt_ang3,a_Pt_ang1*1.88973,a_Pt_ang2*1.88973,a_Pt_ang3*1.88973)
A100_Formaldehyde=np.array([np.ones(len(Ionpos_Formaldehyde_p))*a_Pt_ang1,np.ones(len(Ionpos_Formaldehyde_p))*a_Pt_ang2,np.ones(len(Ionpos_Formaldehyde_p))*a_Pt_ang3])
A100_Ionpos_Methanediol=np.array([np.ones(len(Ionpos_Methanediol_p))*a_Pt_ang1,np.ones(len(Ionpos_Methanediol_p))*a_Pt_ang2,np.ones(len(Ionpos_Methanediol_p))*a_Pt_ang3])
A100_Ionpos_Formic_acid=np.array([np.ones(len(Ionpos_Formic_acid_p))*a_Pt_ang1,np.ones(len(Ionpos_Formic_acid_p))*a_Pt_ang2,np.ones(len(Ionpos_Formic_acid_p))*a_Pt_ang3])
A100_CO2=np.array([np.ones(len(Ionpos_CO2_p))*a_Pt_ang1,np.ones(len(Ionpos_CO2_p))*a_Pt_ang2,np.ones(len(Ionpos_CO2_p))*a_Pt_ang3])


23.52 10.47612863727537 10.47612863727537 44.446449599999994


In [24]:
Ionpos_Formaldehyde_pp=Ionpos_Formaldehyde_p/A100_Formaldehyde.T

In [25]:
Ionpos_Methanediol_pp=Ionpos_Methanediol_p/A100_Ionpos_Methanediol.T

In [26]:
Ionpos_Formic_acid_pp=Ionpos_Formic_acid_p/A100_Ionpos_Formic_acid.T

In [27]:
Ionpos_CO2_pp=Ionpos_CO2_p/A100_CO2.T

In [28]:
for i in range(len(Ionpos_Formaldehyde_pp)):
    print('ion '+ions_Formaldehyde[i], end=' ' )
    for j in range(len(Ionpos_Formaldehyde_pp[i])):
        print("%.3f" % Ionpos_Formaldehyde_pp[i][j], end = ' ')
    print('1 \n')
print('__________________________')
for i in range(len(Ionpos_Methanediol_pp)):
    print('ion '+ions_Methanediol[i], end=' ' )
    for j in range(len(Ionpos_Methanediol_pp[i])):
        print("%.3f" % Ionpos_Methanediol_pp[i][j], end = ' ')
    print('1 \n')
print('__________________________') 
for i in range(len(Ionpos_Formic_acid_pp)):
    print('ion '+ions_Formic_acid[i], end=' ' )
    for j in range(len(Ionpos_Formic_acid_pp[i])):
        print("%.3f" % Ionpos_Formic_acid_pp[i][j], end = ' ')
    print('1 \n')
print('__________________________') 
for i in range(len(Ionpos_CO2_pp)):
    print('ion '+ions_CO2[i], end=' ' )
    for j in range(len(Ionpos_CO2_pp[i])):
        print("%.3f" % Ionpos_CO2_pp[i][j], end = ' ')
    print('1 \n')

ion O 0.000 -0.186 0.075 1 

ion C 0.000 0.000 0.047 1 

ion H 0.000 0.179 0.067 1 

ion H 0.000 0.000 0.000 1 

__________________________
ion O 0.240 -0.020 0.067 1 

ion O -0.099 0.220 0.067 1 

ion C 0.000 0.000 0.046 1 

ion H -0.107 -0.152 0.062 1 

ion H 0.000 0.000 0.000 1 

ion H 0.301 -0.173 0.052 1 

ion H -0.264 0.226 0.052 1 

__________________________
ion H 0.111 0.164 0.000 1 

ion C 0.000 0.000 0.000 1 

ion O 0.058 -0.211 0.000 1 

ion O -0.237 0.049 0.000 1 

ion H -0.332 -0.095 0.000 1 

__________________________
ion C 0.000 0.000 0.000 1 

ion O 0.209 0.000 0.000 1 

ion O -0.209 0.000 0.000 1 



In [29]:
#distance to platinum
Dis_ang=.186*10 #literature value in bohr
Dis=Dis_ang/(a_Pt_ang3) #in units of the lattice constants 


#summing the position of the central atom in the top most layer of  the surface

Dis

0.07908163265306122

In [30]:
Ionpos_Formaldehyde_ppp=Ionpos_Formaldehyde_pp+np.array([0,0,Dis-0.047])+np.array([0.5,0.5,0.1667])
Ionpos_Methanediol_ppp=Ionpos_Methanediol_pp+np.array([0,0,Dis-0.047  ])+np.array([0.5,0.5,0.1667])
Ionpos_Formic_acid_ppp=Ionpos_Formic_acid_pp+np.array([0,0,Dis ])+np.array([0.5,0.5,1.4*0.1667])
Ionpos_CO2_ppp=Ionpos_CO2_pp+np.array([0,0,Dis ])+np.array([0.5,0.5,1.4*0.1667])

In [31]:
for i in range(len(Ionpos_Formaldehyde_ppp)):
    print('ion '+ions_Formaldehyde[i], end=' ' )
    for j in range(len(Ionpos_Formaldehyde_ppp[i])):
        print("%.3f" % Ionpos_Formaldehyde_ppp[i][j], end = ' ')
    print(' 1\n')
print('__________________________')
for i in range(len(Ionpos_Methanediol_ppp)):
    print('ion '+ions_Methanediol[i], end=' ' )
    for j in range(len(Ionpos_Methanediol_ppp[i])):
        print("%.3f" % Ionpos_Methanediol_ppp[i][j], end = ' ')
    print(' 1\n')
print('__________________________')
for i in range(len(Ionpos_Formic_acid_ppp)):
    print('ion '+ions_Formic_acid[i], end=' ' )
    for j in range(len(Ionpos_Formic_acid_ppp[i])):
        print("%.3f" % Ionpos_Formic_acid_ppp[i][j], end = ' ')
    print(' 1')
print('__________________________')
for i in range(len(Ionpos_CO2_ppp)):
    print('ion '+ions_CO2[i], end=' ' )
    for j in range(len(Ionpos_CO2_ppp[i])):
        print("%.3f" % Ionpos_CO2_ppp[i][j], end = ' ')
    print(' 1') 

ion O 0.500 0.314 0.273  1

ion C 0.500 0.500 0.246  1

ion H 0.500 0.679 0.266  1

ion H 0.500 0.500 0.199  1

__________________________
ion O 0.740 0.480 0.266  1

ion O 0.401 0.720 0.266  1

ion C 0.500 0.500 0.245  1

ion H 0.393 0.348 0.260  1

ion H 0.500 0.500 0.199  1

ion H 0.801 0.327 0.251  1

ion H 0.236 0.726 0.251  1

__________________________
ion H 0.611 0.664 0.312  1
ion C 0.500 0.500 0.312  1
ion O 0.558 0.289 0.312  1
ion O 0.263 0.549 0.312  1
ion H 0.168 0.405 0.312  1
__________________________
ion C 0.500 0.500 0.312  1
ion O 0.709 0.500 0.312  1
ion O 0.291 0.500 0.312  1
